
title = "teach"
explain = "教学api"
mode = "dev"
addr = ":8085"
srv = "http://127.0.0.1:8085"


#  hmt 密钥
hmt_key = "key"
# 过期时间 h
hmt_exp = 24

# 系统
# 图片裁剪
image_cut = false
image_width = 800
image_height =600
# 分页
page_min = 5
page_max = 30

# db
#推荐cpu核心数
db_idle = 4
#推荐cpu核心数*2
db_open = 8

# 作者
[author]
name = "zxysilent"
website = "https://github.com/zxysilent"

# 微信
[wechat]
appid = "appid"
secret = "secret"
